// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Orchids - Make something beautiful",
  description:
    "Start, iterate, and launch your website all in one place with Orchids website builder",
  keywords: ["website builder", "AI", "web development", "templates", "orchids"],
  authors: [{ name: "Orchids Team" }],
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        {/* ─────────────────────────────────────────────────────────────────── */}
        {/* Global Header (smaller padding + smaller logo/text) */}
        {/* ─────────────────────────────────────────────────────────────────── */}
        <header className="flex justify-between items-center px-4 py-2 md:px-6 md:py-3 bg-white/5 backdrop-blur-sm">
          <div className="flex items-center gap-1.5 font-semibold text-white">
            <svg
              width="24"
              height="24"
              viewBox="0 0 64 64"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <ellipse cx="32" cy="16" rx="16" ry="16" fill="#E879F9" />
              <ellipse cx="32" cy="48" rx="16" ry="16" fill="#E879F9" />
              <ellipse cx="16" cy="32" rx="16" ry="16" fill="#E879F9" />
              <ellipse cx="48" cy="32" rx="16" ry="16" fill="#E879F9" />
            </svg>
            <span className="text-lg">Orchids</span>
          </div>

          <button className="px-3 py-1.5 border border-white/20 rounded-md bg-transparent text-sm text-white hover:bg-white/10 transition-all">
            Sign in
          </button>
        </header>

        {/** Page content goes here **/}
        {children}
      </body>
    </html>
  );
}
